# Generated by Django 3.2.4 on 2021-07-31 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setparam', '0006_parameteroptpembebanan'),
        ('blending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendingonunit',
            name='persenbiomass',
        ),
        migrations.RemoveField(
            model_name='blendingonunit',
            name='targetkalor',
        ),
        migrations.AddField(
            model_name='blendingonunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 1)),
        ),
        migrations.AddField(
            model_name='blendingonunit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='biomass',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='coal1',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='coal2',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='cofiring',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='settingunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setparam.parameterblending'),
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setparam.unitboiler'),
        ),
    ]
