# Generated by Django 3.2.4 on 2021-08-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blending', '0003_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
