# Generated by Django 3.2.4 on 2021-08-02 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blending', '0004_alter_notes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendingonunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 2)),
        ),
    ]
