# Generated by Django 3.2.4 on 2022-07-27 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blending', '0016_alter_blendingonunit_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendingonunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 28)),
        ),
    ]
