# Generated by Django 3.2.4 on 2022-07-30 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blending', '0019_auto_20220730_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendonunit',
            name='coalflow',
        ),
        migrations.RemoveField(
            model_name='blendonunit',
            name='ggonet',
        ),
        migrations.AlterField(
            model_name='blendingonunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 31)),
        ),
        migrations.AlterField(
            model_name='blendonunit',
            name='tanggal',
            field=models.DateField(default=datetime.date(2022, 7, 31)),
        ),
    ]
