# Generated by Django 3.2.4 on 2022-08-05 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blending', '0020_auto_20220731_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendingonunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 5)),
        ),
        migrations.AlterField(
            model_name='blendonunit',
            name='tanggal',
            field=models.DateField(default=datetime.date(2022, 8, 5)),
        ),
    ]
