# Generated by Django 3.2.4 on 2021-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0003_boilersetting_unitboiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilersetting',
            name='AH',
            field=models.FloatField(default=2.91),
        ),
        migrations.AlterField(
            model_name='boilersetting',
            name='VM',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='boilersetting',
            name='corner',
            field=models.JSONField(default={'corner1AA': [47.8, 48, 28.9, 19.5, 48.4], 'corner1AB': [15.2, 19.9, 19.6, 14.6, 14.6], 'corner1CD': [14.6, 14.2, 39.5, 20.1, 34.9], 'corner1EF': [98.5, 98.5, 98.5, 30, 98.6], 'corner1FF': [19.7, 19.7, 35.4, 59.5, 19.4], 'corner2AA': [99.4, 99.4, 99.4, 30, 99.5], 'corner2AB': [15.8, 20.8, 20.8, 30, 15.8], 'corner2CD': [99.1, 99.1, 99.1, 30, 99.2], 'corner2EF': [98.2, 98.2, 98.3, 30, 98.4], 'corner2FF': [19.5, 19.4, 34.7, 0, 20.1], 'corner3AA': [50.1, 50.3, 30.8, 17.2, 50.2], 'corner3AB': [15.2, 20.1, 20.2, 76.1, 14.9], 'corner3CD': [13.7, 13.4, 39.1, 18.8, 34], 'corner3EF': [98.4, 98.3, 98.3, 30, 98.2], 'corner3FF': [17.7, 11.8, 27.2, 59.6, 15.3], 'corner4AA': [48.2, 49.1, 28.6, 18.3, 48.9], 'corner4AB': [17.5, 20.5, 20.5, 16.1, 15.2], 'corner4CD': [13.7, 13.9, 39.2, 18.6, 34.3], 'corner4EF': [15.9, 17.3, 20.7, 30, 19.2], 'corner4FF': [21.6, 22.1, 36, 60.8, 21.9]}),
        ),
        migrations.AlterField(
            model_name='boilersetting',
            name='dayanet',
            field=models.JSONField(default={'max': 315, 'min': 200}),
        ),
        migrations.AlterField(
            model_name='boilersetting',
            name='nilaikalorunit',
            field=models.CharField(default='5,4000,4200,4500,4600,4700', max_length=100),
        ),
    ]
