# Generated by Django 3.2.4 on 2021-07-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0004_auto_20210623_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterBlending',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='setparam.unitboiler')),
                ('AH', models.FloatField(default=2.91)),
                ('VM', models.IntegerField(default=30)),
                ('nku_size', models.IntegerField()),
                ('nk_unit', models.CharField(max_length=50)),
                ('corner1AA', models.CharField(max_length=50)),
                ('corner2AA', models.CharField(max_length=50)),
                ('corner3AA', models.CharField(max_length=50)),
                ('corner4AA', models.CharField(max_length=50)),
                ('corner1AB', models.CharField(max_length=50)),
                ('corner2AB', models.CharField(max_length=50)),
                ('corner3AB', models.CharField(max_length=50)),
                ('corner4AB', models.CharField(max_length=50)),
                ('corner1CD', models.CharField(max_length=50)),
                ('corner2CD', models.CharField(max_length=50)),
                ('corner3CD', models.CharField(max_length=50)),
                ('corner4CD', models.CharField(max_length=50)),
                ('corner1EF', models.CharField(max_length=50)),
                ('corner2EF', models.CharField(max_length=50)),
                ('corner3EF', models.CharField(max_length=50)),
                ('corner4EF', models.CharField(max_length=50)),
                ('corner1FF', models.CharField(max_length=50)),
                ('corner2FF', models.CharField(max_length=50)),
                ('corner3FF', models.CharField(max_length=50)),
                ('corner4FF', models.CharField(max_length=50)),
            ],
        ),
    ]
