# Generated by Django 3.2.4 on 2021-07-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0005_parameterblending'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterOptPembebanan',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='setparam.unitboiler')),
                ('daya_min', models.IntegerField()),
                ('daya_max', models.IntegerField()),
                ('koef_a_opt_beban', models.DecimalField(decimal_places=2, max_digits=15)),
                ('koef_b_opt_beban', models.DecimalField(decimal_places=2, max_digits=15)),
                ('koef_c_opt_beban', models.DecimalField(decimal_places=2, max_digits=15)),
                ('koef_d_rek_kalor', models.DecimalField(decimal_places=3, max_digits=15)),
                ('koef_e_rek_kalor', models.DecimalField(decimal_places=3, max_digits=15)),
                ('koef_f_rek_kalor', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
