# Generated by Django 3.2.4 on 2021-08-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0006_parameteroptpembebanan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterBoiler',
        ),
    ]
