# Generated by Django 3.2.4 on 2021-09-28 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0007_delete_parameterboiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaPerkiraanBB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(default=9)),
                ('tahun', models.IntegerField(default=2021)),
                ('hbaperton', models.FloatField(max_length=8)),
                ('kursrupiah', models.FloatField(max_length=8)),
                ('hargaperkiraan', models.FloatField(default=0, max_length=20)),
                ('kalori', models.IntegerField(default=4570)),
                ('tm', models.FloatField(default=30.55, max_length=5)),
                ('ts', models.FloatField(default=0.28, max_length=5)),
                ('ash', models.FloatField(default=5.02, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RohUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('roh', models.IntegerField(null=True)),
                ('biaya_pembangkitan', models.FloatField(max_length=15, null=True)),
                ('nphr', models.FloatField(max_length=10, null=True)),
                ('rk', models.IntegerField(null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setparam.unitboiler')),
            ],
        ),
    ]
