# Generated by Django 3.2.4 on 2021-09-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0008_hargaperkiraanbb_rohunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitboiler',
            name='url_coalyard',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='unitboiler',
            name='url_tongkang',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
