# Generated by Django 3.2.4 on 2021-09-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0009_auto_20210929_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargaperkiraanbb',
            name='bulan',
            field=models.IntegerField(default=10),
        ),
    ]
