# Generated by Django 3.2.4 on 2022-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0010_alter_hargaperkiraanbb_bulan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargaperkiraanbb',
            name='bulan',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='hargaperkiraanbb',
            name='tahun',
            field=models.IntegerField(default=2022),
        ),
    ]
