# Generated by Django 3.2.4 on 2022-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0011_auto_20220727_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rohunit',
            name='biaya_pembangkitan',
        ),
        migrations.AddField(
            model_name='rohunit',
            name='coalflow',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rohunit',
            name='ggonet',
            field=models.FloatField(null=True),
        ),
    ]
