# Generated by Django 3.2.4 on 2022-08-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0012_auto_20220731_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargaperkiraanbb',
            name='bulan',
            field=models.IntegerField(default=8),
        ),
    ]
