"""
Django settings for restfulapicrud project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
import  dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))#Path(__file__).resolve().parent.parent

LOGIN_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'q^+8rsdx&2j5bh0v2k(5z3ff9i&i4s$6!fglh+p(ds&-on4msi')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG','True')=='True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS','127.0.0.1,localhost').split(',')+['192.168.100.195']

AUTH_USER_MODEL = "account.Account"
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    'account.backends.CaseInsensitiveModelBackend'
)
# Configure django-excel
# FILE_UPLOAD_HANDLERS = (
#     "Django_excel.ExcelMemoryFileUploadHandler",
#     "Django_excel.TemporaryExcelFileUploadHandler",
# )
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'rest_framework',
    'account',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employeeapi',
    'coaljson',
    'setparam',
    'blending',
    'optpembebanan',
    'api_basic',
    'crispy_forms',
    'reset_migrations',
    'import_export',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    #'pyexcel_xls',
    #'pyexcel_xlsx',


]
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'restfulapicrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restfulapicrud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.postgresql',
         'NAME': 'nemesysnewdb',
         #'NAME': 'restfulapiDB',
         'USER':'postgres',
         'PASSWORD':'76S0l1h@h',
         'HOST':'localhost'

       # 'ENGINE': 'django.db.backends.mysql',
       # 'NAME': 'nemesyswebdb',
       # 'USER': 'nemesys',
        #'PASSWORD':'Ontar10!',
        #'HOST':'192.168.100.195',
        #'PORT':'3306'

        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'restfulapiDB',
        # 'USER':'root',
        # 'PASSWORD':'',
        # 'HOST':'localhost'
    }
}

# DATABASES = {
# 	 'default': {
# 	 'ENGINE': 'django.db.backends.mysql',
# 	 'OPTIONS': {
# 		 'read_default_file': '/website/auth/mysql.cnf',
# 	 },
#  }
# }


if os.environ.get('DATABASE_URL'):
    DATABASES['default']=dj_database_url.config(conn_max_age=600,ssl_require=True)

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATICFILES_DIRS =[
    os.path.join(BASE_DIR,'static')
]
MEDIA_URL='/media/'
MEDIA_ROOT = os.path.join(PROJECT_ROOT,'media')
# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
IMPORT_EXPORT_USE_TRANSACTIONS = True

SESSION_COOKIE_SECURE = True
SESSION_SAVE_EVERY_REQUEST = True


