# Generated by Django 3.2.4 on 2022-07-27 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setparam', '0011_auto_20220727_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemasok', models.CharField(default='not specified', max_length=100)),
                ('kategori_bhn_baku', models.CharField(choices=[('BB', 'Batubara'), ('BIO', 'Biomass')], default='BB', max_length=3)),
                ('kategori', models.CharField(default='not specified', max_length=13)),
                ('kalori', models.IntegerField()),
                ('tm', models.FloatField()),
                ('ts', models.FloatField()),
                ('ash', models.FloatField()),
                ('idtreducing', models.IntegerField()),
                ('sio2', models.FloatField()),
                ('al2o3', models.FloatField()),
                ('fe2o3', models.FloatField()),
                ('cao', models.FloatField()),
                ('mgo', models.FloatField()),
                ('na2o', models.FloatField()),
                ('k2o', models.FloatField()),
                ('tio2', models.FloatField()),
                ('so3', models.FloatField()),
                ('htmax', models.IntegerField()),
                ('jenisabu', models.CharField(default='not specified', max_length=20)),
                ('si', models.FloatField()),
                ('slagging', models.CharField(default='not specified', max_length=10)),
                ('c', models.FloatField()),
                ('h', models.FloatField()),
                ('n', models.FloatField()),
                ('o', models.FloatField()),
            ],
            options={
                'db_table': 'coaljson_coal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoalJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=None)),
            ],
            options={
                'db_table': 'coaljson_coaljson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coalspecdata', models.TextField()),
            ],
            options={
                'db_table': 'coaljson_coalspec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoalStockUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, default=datetime.date(2022, 7, 27))),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('kategori_stock', models.CharField(choices=[('T', 'Tongkang'), ('C', 'Coal Yard')], max_length=2)),
                ('kategori_bhn_baku', models.CharField(choices=[('BB', 'Batubara'), ('BIO', 'Biomass')], max_length=3)),
                ('coalstock', models.TextField(max_length=550)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setparam.unitboiler')),
            ],
            options={
                'db_table': 'coaljson_coalstockunit',
                'managed': False,
            },
        ),
    ]
#https://stackoverflow.com/questions/72425480/why-django-can-not-create-a-table-after-deleting-the-table-and-the-migration-fil