# Generated by Django 3.2.4 on 2022-07-29 00:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setparam', '0011_auto_20220727_2245'),
        ('coaljson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coaljson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coalspec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coalstockunit',
            options={},
        ),
        migrations.AlterModelTable(
            name='coal',
            table=None,
        ),
        migrations.CreateModel(
            name='CoalForBlend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 29, 7, 11, 41, 606585))),
                ('coal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaljson.coal')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setparam.unitboiler')),
            ],
        ),
    ]
