# Generated by Django 3.2.4 on 2022-07-30 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaljson', '0002_auto_20220729_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='coal',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coalforblend',
            name='tanggal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='coalforblend',
            name='waktu',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coalstockunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2022, 7, 30)),
        ),
        migrations.AlterModelTable(
            name='coaljson',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coalspec',
            table=None,
        ),
        migrations.AlterModelTable(
            name='coalstockunit',
            table=None,
        ),
    ]
