# Generated by Django 3.2.4 on 2022-08-05 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaljson', '0004_alter_coalstockunit_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coalstockunit',
            name='tanggal',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 5)),
        ),
    ]
